### ISSUE TITLE
negative refclock_offset value generates alerts

### ISSUE THREAD

**Issue by WaryWolf** [DinoTools/monitoring-check_meinberg_lantime#8]
Hey,

first of all, thanks for making these scripts, we've recently deployed some Meinberg NTP servers and these scripts have helped us add them to our monitoring systems. Great work!

One issue I've noticed is the NTP check alerts any time the reference clock offset is a negative value, e.g.:

```
# perl check_meinberg_lantime_ntp.pl -H ntp1 -C public --refclock-offset-warning=1 --refclock-offset-critical=5 --stratum-critical=2
MBG Lantime NTP OK - State: synchronized Stratum: 1 Refclock Offset: 0.001345ms | stratum=1;;2 refclock-offset=0.001345ms;1;5

...

# perl check_meinberg_lantime_ntp.pl -H ntp1 -C public --refclock-offset-warning=1 --refclock-offset-critical=5 --stratum-critical=2
MBG Lantime NTP CRITICAL - Refclock Offset: -0.000735ms | stratum=1;;2 refclock-offset=-0.000735ms;1;5
```

I didn't look too hard at the Monitoring::Plugin module, so there may be a more elegant solution to this issue, but at least on our end, using `abs()` is a quick fix. I think the magnitude of the offset is the important part, not whether it's positive or negative, so I can't see any drawbacks to this (happy to be corrected).

See https://github.com/DinoTools/monitoring-check_meinberg_lantime/pull/7 for the PR which fixes this in our environment.

**Comment by phibos** [comment]
Thank you for your feedback. I'm able to reproduce the issue.

The thresholds use the threshold syntax. See https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT for more information. In this case you have to specify upper and lower limits.

Example
```
./check_meinberg_lantime_ntp.pl -C public -H  ntp1 --stratum-warning 2 --refclock-offset-warning=-1:1
MBG Lantime NTP OK - State: synchronized Stratum: 1 Refclock Offset: -0.000003ms | stratum=1;2; refclock-offset=-0.000003ms;-1:1;
```

From my point of view we should not use the ```abs()``` function because this will also modify the performance data. But I think most people will provide a simple threshold value. Lets say 2 and would expect a threshold check in the range from -2 to 2. We can simply generate these advanced threshold values.

What do you think?

**Comment by WaryWolf** [comment]
Hey, thanks for the explanation, I should have checked the documentation! I think your PR which converts single value thresholds into the lower:upper syntax is a good usability improvement, in case others have this issue.
